; ==========================================
; Environment untuk ESP32-S3 (Hardware Fisik)
; ==========================================
; Gunakan: pio run -e esp32s3 -t upload -t monitor
[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14

; ==========================================
; Environment untuk ESP32 biasa (Wokwi Simulator)
; ==========================================
; Gunakan: pio run -e esp32dev
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14